### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Git-North** [Git-North/mc-mods-update#2]
- [x] Put everything that isn't gonna be run by the user into a folder
- [x] ~~Make an HTML that gets the latest version of the fabric-installer.jar from [maven-metadata.xml](https://maven.fabricmc.net/net/fabricmc/fabric-installer/maven-metadata.xml)~~ switched to quilt problem solved
   - [x] ~~Somehow use that version info and install the jar~~ cancelled
- [x] Make a symlink
- [x] Use 7zip
  - [x] fix "Can't open file as archive" error
- [x] Merge get-fabric-installer.cmd with Run_me.cmd
- [x] Make it easier to change the path
  - [ ] Merge them
 - [x] [This Thing](https://gist.github.com/jcefoli/fb9400aafee2ac585db3)
 - [x] both fabric and quilt installers
 - [ ] switch to jar instead of exe (turns out fabric installer does come with a java installation and I don't think there is a native installer like quilt so we will use Winget)
 - [x] do smth with the faulty "latest" file (put it on resources?)
 - [ ] output logs
 - [x] get rid of pending_mods
 - [ ] wait 5 seconds for the default selection
 - [ ] check for spaces is file path
 - [ ] make an irm/iex script
 - [ ] https://github.com/nanonestor/universalator/blob/latest/Universalator-2.12.bat#L210C1-L223C38

**Comment by Git-North** [comment]
- [ ] Make it easier to change path
